# Generated by Django 5.1.3 on 2024-12-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='color',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_colors', to='api.productcolor'),
            preserve_default=False,
        ),
    ]
