# Generated by Django 5.1.3 on 2024-11-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='Brand',
        ),
        migrations.AlterModelTable(
            name='brandcategory',
            table='BrandCategory',
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='recommendation',
            table='Recommendation',
        ),
        migrations.AlterModelTable(
            name='skintone',
            table='SkinTone',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
