# Generated by Django 5.1.3 on 2024-11-11 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def add_default_skintones(apps, schema_editor):
    SkinTone = apps.get_model('api', 'SkinTone')
    skintones = [
        {"skintone_name": "Sangat Putih", "skintone_description": "Rentan terhadap sengatan matahari, membutuhkan produk yang lembut dan melembapkan. Carilah produk dengan SPF dan bahan-bahan yang menenangkan seperti lidah buaya dan chamomile."},
        {"skintone_name": "Putih", "skintone_description": "Mudah terbakar, manfaatkan produk yang lembut dengan SPF. Carilah produk dengan antioksidan dan bahan pencerah seperti vitamin C."},
        {"skintone_name": "Putih Kecoklatan", "skintone_description": "Cenderung menjadi cokelat secara bertahap, membutuhkan produk dengan SPF dan hidrasi. Carilah produk dengan keseimbangan bahan yang menghidrasi dan mengeksfoliasi."},
        {"skintone_name": "Sawo Matang", "skintone_description": "Cenderung mudah berjemur, membutuhkan produk dengan SPF dan hidrasi. Carilah produk dengan bahan-bahan yang mencerahkan dan menentang penuaan."},
        {"skintone_name": "Coklat Gelap", "skintone_description": "Jarang terbakar, membutuhkan produk dengan SPF dan hidrasi. Carilah produk dengan bahan pencerah dan pengelupasan kulit."},
        {"skintone_name": "Gelap", "skintone_description": "Jarang terbakar, membutuhkan produk dengan SPF dan hidrasi. Carilah produk dengan bahan pencerah dan pengelupasan kulit."},
        
    ]
    for skintone in skintones:
        SkinTone.objects.create(**skintone)
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_brand_table_alter_brandcategory_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skintone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengguna', to='api.skintone')),
            ],
            options={
                'db_table': 'Pengguna',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RunPython(add_default_skintones),
    ]
