# Generated by Django 5.1.3 on 2024-11-12 15:36

from django.db import migrations, models

def add_default_skintones(apps, schema_editor):
    SkinTone = apps.get_model('api', 'SkinTone')
    skintones = [
        {"skintone_name": "Sangat Putih", "skintone_description": "Rentan terhadap sengatan matahari, membutuhkan produk yang lembut dan melembapkan. Carilah produk dengan SPF dan bahan-bahan yang menenangkan seperti lidah buaya dan chamomile."},
        {"skintone_name": "Putih", "skintone_description": "Mudah terbakar panas matahari, manfaatkan produk yang lembut dengan SPF. Carilah produk dengan antioksidan dan bahan pencerah seperti vitamin C."},
        {"skintone_name": "Putih Kecoklatan", "skintone_description": "Cenderung menjadi cokelat secara bertahap, membutuhkan produk dengan SPF dan hidrasi. Carilah produk dengan keseimbangan bahan yang menghidrasi dan mengeksfoliasi."},
        {"skintone_name": "Sawo Matang", "skintone_description": "Kulit cenderung mudah menjadi coklat, membutuhkan produk dengan SPF dan hidrasi. Carilah produk dengan bahan-bahan yang mencerahkan dan menentang penuaan."},
        {"skintone_name": "Coklat Gelap", "skintone_description": "Jarang terbakar panas matahari, membutuhkan produk dengan SPF dan hidrasi. Carilah produk dengan bahan pencerah dan pengelupasan kulit."},
        {"skintone_name": "Gelap", "skintone_description": "Tidak akan terbakar panas matahari, membutuhkan produk dengan SPF dan hidrasi. Carilah produk dengan bahan pencerah dan pengelupasan kulit."},
        
    ]
    for skintone in skintones:
        SkinTone.objects.create(**skintone)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_skintone_skintone_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skintone',
            name='skintone_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(add_default_skintones),
    ]
